<?php
require_once '../php/auth/roles.php';
requerir_rol(ROL_ESTUDIANTE,'usuario.php');
require_once '../php/solicitudes/solicitudes_servicio.php';
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$uid=(int)usuario_actual()['id_usuario'];$id=(int)($_GET['id']??$_POST['id_solicitud']??0);$mensaje='';$error='';$solicitud=obtener_solicitud_para_cliente($pdo,$id,$uid);
if($_SERVER['REQUEST_METHOD']==='POST'&&$solicitud){$accion=$_POST['accion']??'mensaje';$r=$accion==='mensaje'?enviar_mensaje_solicitud_cliente($pdo,$id,$uid,$_POST['mensaje']??'',$_POST['csrf_token']??'',$_SESSION['csrf_token']):accion_cliente_solicitud($pdo,$id,$uid,$accion,$_SESSION['csrf_token'],$_POST['csrf_token']??'');if($r['ok']){$mensaje=$r['mensaje'];if(!empty($r['id_contratacion'])){header('Location: pasarela-pago.php?id_contratacion='.(int)$r['id_contratacion']);exit;}}else$error=$r['mensaje'];$solicitud=obtener_solicitud_para_cliente($pdo,$id,$uid);}
$mensajes=$solicitud?obtener_mensajes_solicitud($pdo,$id):[];$detalles=$solicitud?json_decode($solicitud['detalles_json']??'{}',true):[];$plantilla=$solicitud?obtener_plantilla_servicio($solicitud['tipo_servicio']??null):null;
$title='Mi solicitud';$description='Detalle de solicitud de servicio.';$cssPrefix='..';$jsPrefix='..';$activePage='cuenta';include '../includes/header.php';
?>
<main class="provider-editor"><?php if(!$solicitud): ?><div class="alert alert-danger">Solicitud no encontrada.</div><?php else: ?><header class="section-heading"><h1><?= htmlspecialchars($solicitud['servicio']) ?></h1><p>Proveedor: <?= htmlspecialchars($solicitud['proveedor_nombre'].' '.$solicitud['proveedor_apellido']) ?> · Estado: <strong><?= htmlspecialchars($solicitud['estado']) ?></strong></p></header><?php if($mensaje): ?><div class="alert alert-success"><?= htmlspecialchars($mensaje) ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-danger"><?= htmlspecialchars($error) ?></div><?php endif; ?>
<section class="content-card"><h2>Tu solicitud</h2><dl class="request-details"><?php foreach($detalles as $k=>$v): ?><div><dt><?= htmlspecialchars($plantilla['campos'][$k]['label']??str_replace('_',' ',ucfirst($k))) ?></dt><dd><?= nl2br(htmlspecialchars((string)$v)) ?></dd></div><?php endforeach; ?></dl><?php if($solicitud['respuesta_proveedor']): ?><h3>Respuesta del proveedor</h3><p><?= nl2br(htmlspecialchars($solicitud['respuesta_proveedor'])) ?></p><?php endif; ?><?php if($solicitud['precio_propuesto']!==null): ?><p><strong>Precio acordado/propuesto:</strong> $<?= number_format((float)$solicitud['precio_propuesto'],2,',','.') ?></p><?php endif; ?><?php if($solicitud['fecha_hora_propuesta']): ?><p><strong>Fecha/horario:</strong> <?= date('d/m/Y H:i',strtotime($solicitud['fecha_hora_propuesta'])) ?></p><?php endif; ?><?php if($solicitud['archivo_adjunto']): ?><p><a class="btn" href="../php/descargas/descargar_archivo.php?tipo=solicitud&id=<?= (int)$solicitud['id_solicitud'] ?>">Descargar archivo enviado</a></p><?php endif; ?></section>
<?php if(in_array($solicitud['estado'],['Aceptada','Contraoferta'],true)): ?><section class="content-card"><h2>Confirmar propuesta</h2><p>Al aceptar se generará una contratación con el precio acordado y pasarás a la pasarela de pago.</p><form method="POST"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="id_solicitud" value="<?= $id ?>"><input type="hidden" name="accion" value="aceptar_propuesta"><button class="btn" type="submit">Aceptar y continuar al pago</button></form><form method="POST"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="id_solicitud" value="<?= $id ?>"><input type="hidden" name="accion" value="cancelar"><button class="link-danger" type="submit">Rechazar / cancelar</button></form></section><?php elseif($solicitud['estado']==='Pendiente'): ?><section class="content-card"><form method="POST"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="id_solicitud" value="<?= $id ?>"><input type="hidden" name="accion" value="cancelar"><button class="link-danger" type="submit">Cancelar solicitud</button></form></section><?php endif; ?>
<section class="content-card"><h2>Conversación</h2><div class="message-thread"><?php foreach($mensajes as $m): ?><article><strong><?= htmlspecialchars($m['nombre'].' '.$m['apellido']) ?></strong><time><?= date('d/m/Y H:i',strtotime($m['fecha_mensaje'])) ?></time><p><?= nl2br(htmlspecialchars($m['mensaje'])) ?></p></article><?php endforeach; ?></div><form method="POST"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="id_solicitud" value="<?= $id ?>"><input type="hidden" name="accion" value="mensaje"><textarea name="mensaje" rows="3" required placeholder="Responder al proveedor"></textarea><button class="btn" type="submit">Enviar mensaje</button></form></section><a class="btn" href="mis-solicitudes-servicios.php">Volver</a><?php endif; ?></main><?php include '../includes/footer.php'; ?>
