<?php
require_once __DIR__ . '/../config/database.php';
function column_exists(PDO $pdo,string $table,string $column):bool{$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t AND COLUMN_NAME=:c");$s->execute(['t'=>$table,'c'=>$column]);return(bool)$s->fetchColumn();}
function constraint_exists(PDO $pdo,string $table,string $constraint):bool{$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME=:t AND CONSTRAINT_NAME=:c");$s->execute(['t'=>$table,'c'=>$constraint]);return(bool)$s->fetchColumn();}
function add_column(PDO $pdo,string $table,string $column,string $definition):void{if(!column_exists($pdo,$table,$column)){$pdo->exec("ALTER TABLE `{$table}` ADD COLUMN `{$column}` {$definition}");echo "Agregada {$table}.{$column}\n";}}
try{
$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
add_column($pdo,'categorias','creada_por','INT NULL AFTER descripcion');
if(!constraint_exists($pdo,'categorias','fk_categorias_creador'))$pdo->exec("ALTER TABLE categorias ADD CONSTRAINT fk_categorias_creador FOREIGN KEY (creada_por) REFERENCES usuarios(id_usuario) ON DELETE SET NULL ON UPDATE CASCADE");
$pdo->exec("ALTER TABLE publicaciones MODIFY estado ENUM('Activo','Inactivo','Pausado','Eliminado') NOT NULL DEFAULT 'Activo'");
add_column($pdo,'publicaciones','cupos','INT NULL AFTER duracion_horas');
add_column($pdo,'publicaciones','disponibilidad','TEXT NULL AFTER cupos');
add_column($pdo,'publicaciones','tipo_servicio','VARCHAR(60) NULL AFTER disponibilidad');
add_column($pdo,'publicaciones','eliminado_en','DATETIME NULL AFTER imagen');
add_column($pdo,'publicaciones','fecha_actualizacion','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER fecha_creacion');
$pdo->exec("CREATE TABLE IF NOT EXISTS perfiles_profesionales (id_perfil INT AUTO_INCREMENT PRIMARY KEY,id_usuario INT NOT NULL UNIQUE,titulo_profesional VARCHAR(180) NULL,presentacion TEXT NULL,experiencia TEXT NULL,formacion TEXT NULL,certificaciones TEXT NULL,habilidades TEXT NULL,especialidades TEXT NULL,idiomas VARCHAR(255) NULL,ubicacion VARCHAR(150) NULL,modalidad_trabajo VARCHAR(150) NULL,portfolio_url VARCHAR(255) NULL,linkedin_url VARCHAR(255) NULL,tiempo_respuesta VARCHAR(100) NULL,visibilidad ENUM('Registrados','Relacionados') NOT NULL DEFAULT 'Registrados',actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_perfiles_profesionales_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS curso_modulos (id_modulo INT AUTO_INCREMENT PRIMARY KEY,id_publicacion INT NOT NULL,titulo VARCHAR(180) NOT NULL,descripcion TEXT NULL,orden INT NOT NULL DEFAULT 1,CONSTRAINT fk_curso_modulos_publicacion FOREIGN KEY (id_publicacion) REFERENCES publicaciones(id_publicacion) ON DELETE CASCADE ON UPDATE CASCADE,INDEX idx_curso_modulos_publicacion_orden (id_publicacion,orden)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS curso_unidades (id_unidad INT AUTO_INCREMENT PRIMARY KEY,id_modulo INT NOT NULL,titulo VARCHAR(180) NOT NULL,descripcion TEXT NULL,orden INT NOT NULL DEFAULT 1,CONSTRAINT fk_curso_unidades_modulo FOREIGN KEY (id_modulo) REFERENCES curso_modulos(id_modulo) ON DELETE CASCADE ON UPDATE CASCADE,INDEX idx_curso_unidades_modulo_orden (id_modulo,orden)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS curso_recursos (id_recurso INT AUTO_INCREMENT PRIMARY KEY,id_unidad INT NOT NULL,titulo VARCHAR(180) NOT NULL,tipo ENUM('Archivo','PDF','Imagen','Video','Enlace') NOT NULL,url VARCHAR(500) NULL,archivo VARCHAR(255) NULL,descripcion TEXT NULL,orden INT NOT NULL DEFAULT 1,fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_curso_recursos_unidad FOREIGN KEY (id_unidad) REFERENCES curso_unidades(id_unidad) ON DELETE CASCADE ON UPDATE CASCADE,INDEX idx_curso_recursos_unidad_orden (id_unidad,orden)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("ALTER TABLE solicitudes MODIFY estado ENUM('Pendiente','Aceptada','Rechazada','Contraoferta','En Proceso','Realizada','Cancelada') NOT NULL DEFAULT 'Pendiente'");
add_column($pdo,'solicitudes','detalles_json','JSON NULL AFTER estado'); add_column($pdo,'solicitudes','archivo_adjunto','VARCHAR(255) NULL AFTER detalles_json'); add_column($pdo,'solicitudes','precio_propuesto','DECIMAL(10,2) NULL AFTER archivo_adjunto'); add_column($pdo,'solicitudes','fecha_hora_propuesta','DATETIME NULL AFTER precio_propuesto'); add_column($pdo,'solicitudes','respuesta_proveedor','TEXT NULL AFTER fecha_hora_propuesta'); add_column($pdo,'solicitudes','id_contratacion','INT NULL AFTER id_publicacion'); add_column($pdo,'solicitudes','fecha_actualizacion','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER fecha_solicitud');
if(!constraint_exists($pdo,'solicitudes','fk_solicitudes_contratacion'))$pdo->exec("ALTER TABLE solicitudes ADD CONSTRAINT fk_solicitudes_contratacion FOREIGN KEY (id_contratacion) REFERENCES contrataciones(id_contratacion) ON DELETE SET NULL ON UPDATE CASCADE");
$pdo->exec("CREATE TABLE IF NOT EXISTS solicitud_mensajes (id_mensaje INT AUTO_INCREMENT PRIMARY KEY,id_solicitud INT NOT NULL,id_usuario INT NOT NULL,mensaje TEXT NOT NULL,fecha_mensaje DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_solicitud_mensajes_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitudes(id_solicitud) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT fk_solicitud_mensajes_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,INDEX idx_solicitud_mensajes_fecha (id_solicitud,fecha_mensaje)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("UPDATE publicaciones SET tipo_servicio='impresion_3d' WHERE id_publicacion=2 AND tipo='Servicio' AND tipo_servicio IS NULL");
$pdo->exec("UPDATE publicaciones SET tipo_servicio='mentoria' WHERE id_publicacion=4 AND tipo='Servicio' AND tipo_servicio IS NULL");
$pdo->exec("UPDATE publicaciones SET tipo_servicio='formacion_institucional' WHERE id_publicacion=10 AND tipo='Servicio' AND tipo_servicio IS NULL");
echo "Migración de funciones docente/proveedor completada.\n";
}catch(Throwable $e){fwrite(STDERR,"Error de migración: ".$e->getMessage()."\n");exit(1);}
