name: "📝 Validar formato del título del PR"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  conventional-commits:
    name: "Validar Conventional Commits en Título de PR"
    runs-on: ubuntu-latest

    steps:
      - name: Validar título del PR
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
